### ISSUE TITLE
Initialize Method

### ISSUE THREAD

**Issue by SageBeard** [SageBeard/Kele#1]
I'm working on Checkpoint 2 of my Kele app where I create my own Kele gem. I've set up the Kele gem, however now I need to initialize it. I've created an initialize method that will create a new client with a username and password. However, every time I try to create a new client I get the following error message. 
 
<img width="544" alt="screen shot 2017-08-13 at 4 45 26 pm" src="https://user-images.githubusercontent.com/20909943/29254278-d703d27a-8046-11e7-9377-6396cae66c53.png">
kele.rb

```
require 'httparty'
require 'json'


class Kele
  include HTTParty
  base_uri 'https://www.bloc.io/api/v1'

  def initialize(email, password)
    options = {
      body: { email: email, password: password } }
    response = self.class.post('/sessions', options)
    @auth_token = response['auth_token']
    if @auth_token.nil?
      puts "Sorry, invalid credentials."
    end
  end
end
```

**Comment by bdougie** [comment]
I believe it is due to an error in your code, the following is invalid and not being used.

```
base_uri 'https://www.bloc.io/api/v1'
```
The ultimate goal is to use the base_uri in your post request. 

```
    response = self.class.post('https://www.bloc.io/api/v1/sessions', options)

```

So perhaps make the base_uri a variable
```
base_uri = 'https://www.bloc.io/api/v1'

```

**Comment by SageBeard** [comment]
I've tried a few different string concatenation methods and am still getting the same error above with the wrong number of arguments. Any idea what else could be the issue? 

````
require 'httparty'
require 'json'


class Kele
  include HTTParty
  base_uri = 'https://www.bloc.io/api/v1'

  def initialize(email, password)
    options = {
      body: { email: email, password: password } }
    response = self.class.post('#{base_uri}' + '/sessions', options)
    @auth_token = response['auth_token']
    if @auth_token.nil?
      puts "Sorry, invalid credentials."
    end
  end
end
```

**Comment by bdougie** [comment]
String interpolation has to be double quotes to work

**Comment by SageBeard** [comment]
I put everything in double quotes and still no luck.

```
require "httparty"
require "json"


class Kele
  include HTTParty
  base_uri = "https://www.bloc.io/api/v1"

  def initialize(email, password)
    options = {
      body: { email: email, password: password } }
    response = self.class.post("#{base_uri}" + "/sessions", options)
    @auth_token = response["auth_token"]
    if @auth_token.nil?
      puts "Sorry, invalid credentials."
    end
  end
end
```

**Comment by bdougie** [comment]
try this instead:
```rb
    response = self.class.post("#{base_uri}/sessions", options)
```

**Comment by SageBeard** [comment]
No luck. Is there a step before initialization that I need to be doing?

**Comment by bdougie** [comment]
You should be getting a different error now, which is complaining about not finding the variable base_uri. This is because Ruby Classes share data in methods and not variables:

```
require 'httparty'
require 'json'


class Kele
  include HTTParty

  def base_uri
    'https://www.bloc.io/api/v1'
  end

  def initialize(email, password)
    options = {
      body: { email: email, password: password }
    }
    response = self.class.post("#{base_uri}/sessions", options)
    @auth_token = response['auth_token']
    if @auth_token.nil?
      puts "Sorry, invalid credentials."
    end
  end
end
```

**Comment by SageBeard** [comment]
I'm still getting the same error message

**Comment by bdougie** [comment]
The above code works without issue for. Is your latest code on a branch on GitHub?

**Comment by SageBeard** [comment]
Yes, its on master

**Comment by bdougie** [comment]
Just pulled latest master and got this:

```rb
$ irb
2.3.0 :001 > require './lib/kele'
 => true 
2.3.0 :002 > Kele.new("brian@netlify.com", "foo")
Sorry, invalid credentials.
 => #<Kele:0x007fa038a83290 @auth_token=nil> 
2.3.0 :003 > 
```

Is this not what you see?

**Comment by SageBeard** [comment]
Ah ok, so I was entering " require 'kele.rb' " -- when I previously tried to enter './lib/kele' it wasn't working for me. But, now it is and I got your same response above.

**Comment by bdougie** [comment]
cool 🙌🏾
