### ISSUE TITLE
Retrieve User

### ISSUE THREAD

**Issue by SageBeard** [SageBeard/Kele#2]
I'm working on my checkpoint 3 of the Kele app where I retrieve the current user through get_me function. I've set-up get_me and the JSON gem as a runtime dependency. When I try to retrieve the user data, I'm getting the following error. 

My first question is if I am setting this up wrong since I'm getting invalid credentials when I enter the new client? (kele_client = Kele.new("jane@gmail.com", "abc123"))
My second issue is I can't figure out what the "undefined method `strip' " is referencing when I enter kele_client.get_me
```
require 'httparty'
require 'json'


class Kele
  include HTTParty

  def base_uri
    'https://www.bloc.io/api/v1'
  end

  def initialize(email, password)
    options = {
      body: { email: email, password: password }
    }
    response = self.class.post("#{base_uri}/sessions", options)
    @auth_token = response['auth_token']
    if @auth_token.nil?
      puts "Sorry, invalid credentials."
    end
  end

  def get_me
    response = self.class.get("#{base_uri}/users/me", headers: { "authorization" => @auth_token })
    JSON.parse(response.body)
  end
end
```

<img width="693" alt="screen shot 2017-08-21 at 7 30 24 am" src="https://user-images.githubusercontent.com/20909943/29543821-b9fffaac-8698-11e7-91c4-2333d0fd48ce.png">

**Comment by bdougie** [comment]
The undefined method strip is because you aren't actually logging in an account successfully. You should be using your "real" email and password for logging into Bloc. i.e.

```rb
Kele.new("theRealSage@gmail.com", "your actual Bloc password")
```
